### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by Hyosssssun** [Hyosssssun/currencyExchanger#33]
- [https://pagepro.co/blog/publishing-expo-react-native-app-to-ios-and-android/](https://pagepro.co/blog/publishing-expo-react-native-app-to-ios-and-android/)
- [https://docs.expo.dev/classic/building-standalone-apps/](https://docs.expo.dev/classic/building-standalone-apps/)
- [https://docs.expo.dev/build/setup/](https://docs.expo.dev/build/setup/)

**Comment by sandiskolarczyk** [comment]
https://docs.expo.dev/distribution/publishing-websites/
